remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: GarminThermoNest
description: An application for Garmin watches that allows you to control your Nest thermostat.
logo: './doc/images/gcp_icon.png'
show_downloads: false