remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: GarminThermoNest
description: An app for garmin watches that allows you to controll your thermostat.
logo: './doc/images/gcp_icon.png'
show_downloads: false